sections:
  main:
    display: Utama
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: foto
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Foto
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: link_website
        field:
          input_type: text
          antlers: false
          display: 'Link Website'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: deskripsi
        field:
          antlers: false
          display: Deskripsi
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: App
